DROP SCHEMA IF EXISTS nexus CASCADE;
DROP SCHEMA IF EXISTS nexus_it CASCADE;
DROP SCHEMA IF EXISTS techwave CASCADE;
DROP SCHEMA IF EXISTS finstar CASCADE;
DROP SCHEMA IF EXISTS nexus_food CASCADE;
DROP SCHEMA IF EXISTS guardforce CASCADE;
